apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'products'
        metrics_path: '/q/metrics/'
        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s
        static_configs:
          - targets: ['products:10000']
            labels:
              group: 'dev'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-configmap
